### ISSUE TITLE
Add Sign bat

### ISSUE THREAD

**Issue by RuthlessRuler** [appium/sign#8]
Adding a batch file called SignApk.bat with following code:
`@echo off
if "%PATH_BASE%" == "" set PATH_BASE=%PATH%
set PATH=%CD%;%PATH_BASE%;
chcp 65001 2>nul >nul
java -jar -Duser.language=en -Dfile.encoding=UTF8 "%~dp0\sign.jar" %*`

Will replace the whole writing of java -jar stuff and replace it by only signapk.
Would be nice!

**Comment by bootstraponline** [comment]
I think sign.jar isn't used anymore. Google released native signing binaries as part of the Android SDK.

I agree signapk.bat is cleaner. 🙂

**Comment by RuthlessRuler** [comment]
Well, its actually used by many people who are doing basic apk modding! 
Since it wouldn't do any harm, I highly suggest to add it as it makes its easier to use the tool!

**Comment by bootstraponline** [comment]
That's awesome. Send a pull request and I'll merge it. 🙂
